### PR TITLE
Switch to Ammonite 0.5.7

### PR DESCRIPTION
**Pull request by williamho**
First version with Scala 2.11.8 compatibility

### CODE REVIEW

**Comment by alexarchambault** [comment]
Missed that one, sorry. Merging, thanks (for the README update too)!

**Comment by williamho** [comment]
Any plans for a release?

**Comment by swsnr** [comment]
Indeed, a release would be great; the current release doesn't work with Scala 2.11.8 :cry:

**Comment by alexarchambault** [comment]
`0.1.2` is released (depends on Ammonite `0.6.0` by default). See the README for how to manually bump the Ammonite version.

**Comment by swsnr** [comment]
@alexarchambault ❤️ Thank you very very much!

**Pull request merged**
